-- File generated by the BNF Converter (bnfc 2.9.3).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language LispVal.

module LispVal.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Prog = Prog [LispVal]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LispVal
    = Atom Ident
    | String String
    | Number LispNumber
    | Bool LispBool
    | Nil
    | Quote LispVal
    | SExp [LispVal]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype LispBool = LispBool String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype LispNumber = LispNumber String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

